name: Update Nix Flake

on:
  schedule:
    - cron: "0 0 * * 6" # Runs at 00:00 UTC every Saturday
  workflow_dispatch: # Also run manually

jobs:
  update-flake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Nix
        uses: cachix/install-nix-action@v22

      - name: Update Nix flake
        run: nix flake update

      # TODO: Check requires to unlock secrets.json
      # - name: Check Nix Flake
      #   run: nix flake check

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update Nix flake"
          branch: "chore/update-flake-{{date 'YYYYMMDD'}}"
          title: "Update Nix flake - {{date 'YYYYMMDD'}}"
          body: "This PR updates the Nix flake."
          base: main
          delete-branch: true  # Optionally delete the branch after the PR is merged