name: Update Nix Flake

on:
  schedule:
    - cron: "0 0 * * 6" # Runs at 00:00 UTC every Saturday

jobs:
  update-flake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Nix
        uses: cachix/install-nix-action@v22

      - name: Update Nix flake
        run: nix flake update

      # TODO: Check requires to unlock secrets.json
      # - name: Check Nix Flake
      #   run: nix flake check

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create a new branch
        id: create_branch
        run: |
          BRANCH_NAME="chore/$(date +'%Y%m%d')__update"
          git checkout -b $BRANCH_NAME
          echo "::set-output name=branch_name::$BRANCH_NAME"

      - name: Commit the updated flake
        run: |
          git add .
          git commit -m "Update Nix flake"

      - name: Push branch to the repository
        run: |
          git push origin ${{ steps.create_branch.outputs.branch_name }}

      - name: Create a pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.create_branch.outputs.branch_name }}
          title: "Update Nix flake - ${{ steps.create_branch.outputs.branch_name }}"
          body: "This PR updates the Nix flake."
          base: main
