name: Update Nix Flake

on:
  schedule:
    - cron: "0 6 * * sat" # Runs at at 06:00 UTC every Saturday
  workflow_dispatch: # Also run manually

jobs:
  update-flake:
    runs-on: ubuntu-latest

    steps:
      - name: Condition check # checks for first Sat of month if job started on schedule
        id: condition_check
        run: |
          if [[ "${{ github.event_name }}" == "schedule" && $(date "+%d") -le 7 ]]; then 
            echo "condition_check=true" >> $GITHUB_ENV
          else
            echo "condition_check=false" >> $GITHUB_ENV
          fi

      - name: Checkout repository
        if: ${{ env.condition_check == 'true' }}
        uses: actions/checkout@v3

      - name: Set up Nix
        if: ${{ env.condition_check == 'true' }}
        uses: cachix/install-nix-action@v22

      - name: Update Nix flake
        if: ${{ env.condition_check == 'true' }}
        run: nix flake update

      # TODO: Check requires to unlock secrets.json
      # - name: Check Nix Flake
      #   run: nix flake check

      - name: Set date
        if: ${{ env.condition_check == 'true' }}
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Create Pull Request
        if: ${{ env.condition_check == 'true' }}
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          committer: GitHub <noreply@github.com>
          author: GitHub <noreply@github.com>
          commit-message: "Update Nix flake"
          branch: "chore/update-flake-${{ env.date }}"
          title: "Update Nix flake - ${{ env.date }}"
          body: "This PR updates the Nix flake."
          base: main
          delete-branch: true  # Optionally delete the branch after the PR is merged